/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiwayatRouteImport } from './routes/riwayat'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as PegawaiRouteImport } from './routes/pegawai'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LaporanBaruRouteImport } from './routes/laporan.baru'

const RiwayatRoute = RiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const PegawaiRoute = PegawaiRouteImport.update({
  id: '/pegawai',
  path: '/pegawai',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanBaruRoute = LaporanBaruRouteImport.update({
  id: '/laporan/baru',
  path: '/laporan/baru',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pegawai': typeof PegawaiRoute
  '/pengaturan': typeof PengaturanRoute
  '/riwayat': typeof RiwayatRoute
  '/laporan/baru': typeof LaporanBaruRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pegawai': typeof PegawaiRoute
  '/pengaturan': typeof PengaturanRoute
  '/riwayat': typeof RiwayatRoute
  '/laporan/baru': typeof LaporanBaruRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pegawai': typeof PegawaiRoute
  '/pengaturan': typeof PengaturanRoute
  '/riwayat': typeof RiwayatRoute
  '/laporan/baru': typeof LaporanBaruRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pegawai'
    | '/pengaturan'
    | '/riwayat'
    | '/laporan/baru'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pegawai'
    | '/pengaturan'
    | '/riwayat'
    | '/laporan/baru'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pegawai'
    | '/pengaturan'
    | '/riwayat'
    | '/laporan/baru'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  PegawaiRoute: typeof PegawaiRoute
  PengaturanRoute: typeof PengaturanRoute
  RiwayatRoute: typeof RiwayatRoute
  LaporanBaruRoute: typeof LaporanBaruRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/riwayat': {
      id: '/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof RiwayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pegawai': {
      id: '/pegawai'
      path: '/pegawai'
      fullPath: '/pegawai'
      preLoaderRoute: typeof PegawaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/baru': {
      id: '/laporan/baru'
      path: '/laporan/baru'
      fullPath: '/laporan/baru'
      preLoaderRoute: typeof LaporanBaruRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  PegawaiRoute: PegawaiRoute,
  PengaturanRoute: PengaturanRoute,
  RiwayatRoute: RiwayatRoute,
  LaporanBaruRoute: LaporanBaruRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
